// import '@/plugins/laravel-echo'
import '@/plugins/toast'
import '@/plugins/v-calendar'
import '@/plugins/v-mask'
import '@/plugins/v-tooltip'
import '@/plugins/vee-validate'
import '@/plugins/vue-final-modal'
// import '@/plugins/vue-nestable'
import '@/plugins/font-awesome'
import '@/plugins/vue-number-animation'
import '@/plugins/vue-select'
import '@/plugins/vue-slide-up-down'

